version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: webServer
    ports:
      - "8443:443"
    volumes:
      # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
      - ./nginx:/etc/nginx/conf.d/
    links:
      - app
  app:
    build:
      context: .
      dockerfile: ./fretre/Dockerfile