name: Server CD to STG

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      EC2_SECURITY_GROUP_ID:
        required: true
      GIT_PRIVATE_KEY:
        required: true
      USER_NAME:
        required: true
      HOST_NAME:
        required: true
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # IP取得ライブラリをインストール
      - name: Public IP Install
        id: ip
        uses: haythem/public-ip@v1.3

      # BranchをCheckout
      - name: Checkout
        uses: actions/checkout@v4

      # GCPの認証
      - name: Auth GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      # gcloud sdk 設定
      - name: Setup Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Deploy with gcloud"
        run: |
          gcloud compute ssh taichis844@fretre-notification-instance \
          --zone us-west1-a \
          --quiet \
          --command='
            cd app/FreTreBackEnd && 
            git fetch
            git checkout ${{ github.ref_name }}
            git pull
            bash FreTreAp
            iCore/conte/scripts/deploy_payara_server.sh
          '

      # # AWS CLIをインストールする
      # - name: AWS CLI install
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install --update
      #     aws --version

      # # AWS CLIにキーを設定をする
      # - name: AWS set Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-southeast-2

      # # デプロイする
      # - name: Deploy
      #   run: |

      #     # SSHのセキュリティグループを開放する
      #     aws ec2 authorize-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      #     # SSH接続して、git pullする
      #     echo "${{ secrets.GIT_PRIVATE_KEY }}" > private_key
      #     chmod 600 private_key
      #     ssh -oStrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "cd /home/ec2-user/app/FreTreBackEnd && git fetch --prune && git checkout main && git pull origin main && ./FreTreApiCore/conte/scripts/deploy.sh -e stg"

      #     # SSHのセキュリティグループを閉じる
      #     aws ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
