name: Server CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - name: Build with maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Move artifacts for upload
        if: ${{ success() }} && github.ref == 'main'
        run: mkdir staging && cp target/*.{jar,war} staging

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
